project/apps/captable/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'apps.captable.views',

    url(r'liquidation/$', 'liquidation_instructions', name='liquidation_instructions'),
    url(r'financing/$', 'financing_instructions', name='financing_instructions'),

    url(r'summary/$', 'summary', name='summary'),
    url(r'liquidation/(?P<purchase_price>\d+)$', 'liquidation_summary', name='liquidation_summary'),
    url(r'financing/(?P<new_money>\d+),(?P<pre_valuation>\d+),(?P<pool_rata>\d+)$', 'financing_summary', name='financing_summary'),

    url(r'security/$', 'security_list', name='security_list'),
    url(r'investor/$', 'investor_list', name='investor_list'),
    url(r'certificate/$', 'certificate_list', name='certificate_list'),

    url(r'security/(?P<security>[\w-]+)/$', 'security_detail', name='security_detail'),
    url(r'certificate/(?P<certificate>[\w-]+)/$', 'certificate_detail', name='certificate_detail'),
    url(r'investor/(?P<investor>[\w-]+)/$', 'investor_detail', name='investor_detail'),
)

project/apps/entries/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'apps.entries.views',

    url(r'security/$', 'security_list', name='security_list'),
    url(r'investor/$', 'investor_list', name='investor_list'),
    url(r'shareholder/$', 'shareholder_list', name='shareholder_list'),
    url(r'certificate/$', 'certificate_list', name='certificate_list'),

    url(r'security/(?P<security>[\w-]+)/$', 'security_detail', name='security_detail'),
    url(r'certificate/(?P<certificate>[\w-]+)/$', 'certificate_detail', name='certificate_detail'),
    url(r'investor/(?P<investor>[\w-]+)/$', 'investor_detail', name='investor_detail'),
    url(r'shareholder/(?P<shareholder>[\w-]+)/$', 'shareholder_detail', name='shareholder_detail'),
)

project/captable/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'captable.views',

    url(r'^$', 'home', name='home'),

    url(r'company/(?P<company>[\w-]+)/$', 'company', name='company'),

    url(r'company/(?P<company>[\w-]+)/summary/$', 'summary', name='summary'),

    url(r'company/(?P<company>[\w-]+)/liquidation/(?P<purchase_price>\d+)$', 'liquidation', name='liquidation'),

    url(r'company/(?P<company>[\w-]+)/financing/(?P<new_money>\d+),(?P<pre_valuation>\d+),(?P<pool_rata>\d+)', 'financing', name='financing'),

    url(r'company/(?P<company>[\w-]+)/security/$', 'securities', name='securities'),
    url(r'company/(?P<company>[\w-]+)/investor/$', 'investors', name='investors'),
    url(r'company/(?P<company>[\w-]+)/shareholder/$', 'shareholders', name='shareholders'),
    url(r'company/(?P<company>[\w-]+)/certificate/$', 'certificates', name='certificates'),

    url(r'company/(?P<company>[\w-]+)/security/(?P<security>[\w-]+)/$', 'security', name='security'),
    url(r'company/(?P<company>[\w-]+)/certificate/(?P<certificate>[\w-]+)/$', 'certificate', name='certificate'),
    url(r'company/(?P<company>[\w-]+)/investor/(?P<investor>[\w-]+)/$', 'investor', name='investor'),
    url(r'company/(?P<company>[\w-]+)/shareholder/(?P<shareholder>[\w-]+)/$', 'shareholder', name='shareholder'),

)

project/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.views.generic import TemplateView

urlpatterns = patterns(
    '',
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.captable.urls',)),
)

urlpatterns += staticfiles_urlpatterns()

project/apps/captable/models.py
from __future__ import division

import datetime
from dateutil.relativedelta import relativedelta

from django.db import models
from django.db.models import Sum, Max
from django.db.models.query import QuerySet
from django.core.urlresolvers import reverse
from django.conf import settings

from django.utils.text import slugify

from model_utils.managers import PassThroughManager

from .constants import *

from .managers import (
    SecurityQuerySet,
    CertificateQuerySet,
    share_price,
    proforma as proforma2
)

class Investor(models.Model):
    """Investor represents the entity making the decision to invest.

    Examples of investors are VC firms, angels, banks, note holders,
    friends, family and fools.
    """

    name = models.CharField(max_length=200, help_text="""
        The name of the investor, which may be the same as the shareholder
        name.  For VCs, this would be the name of the VC firm itself.""")
    slug = models.SlugField(unique=True, help_text="""
        The slug is the slugified version of the investor name, is unique,
        and is used in composing the URL for the investor.""")
    contact = models.CharField(max_length=200, blank=True, help_text="""
        If the investor is a professional firm, the contact is the name
        to whom correspondance at the firm should be directed.""")
    address = models.CharField(max_length=200, blank=True, help_text="""
        The street address of the investor.""")
    city = models.CharField(max_length=200, blank=True, help_text="""
        The mailing city of the investor.""")
    state = models.CharField(max_length=2, blank=True, help_text="""
        The mailing state (two-letter abbreviation) of the investor.""")
    zipcode = models.CharField(max_length=20, blank=True, help_text="""
        The mailing zipcode of the investor.""")
    notes = models.TextField(blank=True, help_text="""
        A free-form notes field added for convenience.""")

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(unicode(self.name))
        super(Investor, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('investor_detail', args=[str(self.slug)])

    def proceeds(self, purchase_price):
        certificates = Certificate.objects.filter(
            shareholder__investor=self)
        return sum(filter(None, [c.proceeds(purchase_price) for c in certificates]))

    @property
    def liquidated(self):
        certificates = Certificate.objects.filter(
            shareholder__investor=self)
        return sum(filter(None, [c.liquidated for c in certificates]))

    @property
    def outstanding(self):
        certificates = Certificate.objects.filter(
            shareholder__investor=self)
        return sum(filter(None, [c.outstanding for c in certificates]))

    @property
    def paid(self):
        certificates = Certificate.objects.filter(
            shareholder__investor=self)
        return sum(filter(None, [c.paid for c in certificates]))

    @property
    def preference(self):
        certificates = Certificate.objects.filter(
            shareholder__investor=self)
        return sum(filter(None, [c.preference for c in certificates]))

    def proceeds_rata(self, purchase_price):
        proceeds = self.proceeds(purchase_price)
        total = Certificate.objects.select_related().proceeds(purchase_price)
        return proceeds / total

    def prorata(self, new_shares):
        certificates = Certificate.objects.filter(
            shareholder__investor=self)
        return sum(filter(None, [c.prorata(new_shares) for c in certificates]))

    def exchanged(self, pre_valuation=None, price=None):
        certificates = Certificate.objects.filter(
            shareholder__investor=self)
        return sum(filter(None, [c.exchanged(pre_valuation, price) for c in certificates]))


class Shareholder(models.Model):
    """Shareholder is the legal entity which holds the security.

    Shareholder represents the legal entity which provides
    the actual fund source and is the legal owner.  In the case of a VC firm,
    this would be the fund (generally organized as a LP), or if
    an Angel could be represented by a trust or other financial vehicle.
    """
    name = models.CharField(max_length=200, help_text="""
        The legal name of the shareholder.  In the case of venture investment,
        this would be the formal, legal name of the fund.""")
    investor = models.ForeignKey(Investor, help_text="""
        Every shareholder must a parent Investor.""")

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name



class Security(models.Model):
    """Security represents an specific financing instrument.

    A Security represents a specific financing instrument, and is usually
    accompanied by its own form of legal documentation.  Examples of
    securities include common stock, a Series A offering, a covertible
    loan, etc.  Securities can be similiar but have different terms,
    such as a Series A offering and a Series B offering, both of which
    are preferred stock but may have different prices or preferences.
    """

    SECURITY_TYPE = (
        ('Equity', (
            (SECURITY_TYPE_COMMON, 'Common'),
            (SECURITY_TYPE_PREFERRED, 'Preferred'),
            )
        ),
        ('Debt', (
            (SECURITY_TYPE_CONVERTIBLE, 'Convertible'),
            )
        ),
        ('Rights', (
            (SECURITY_TYPE_OPTION, 'Option'),
            (SECURITY_TYPE_WARRANT, 'Warrant'),
            )
        ),
    )

    name = models.CharField(max_length=50, help_text="""
        The name of the round of funding.
        Usual names are Common Stock, Series A, Series Seed, Founder Stock,
        Bridge Loan, Option Round A, Bridge Warrants, Convertible,
        or any other way to which the security is commonly referred.""")
    slug = models.SlugField(unique=True, help_text="""
        The slug is automatically generated based on the security name,
        which you can overwrite.""")
    date = models.DateField(default=datetime.date.today, help_text="""
        The date the security was created by the board.""")
    security_type = models.IntegerField(max_length=20, choices=SECURITY_TYPE, help_text="""
        The specific type of the security issued.  Choices are:
        - Common Stock.  This stock is typically issued to founders and employees.
        - Preferred Stock.  This stock is typically issued to investors.
        - Convertible Debt.  This is a loan that converts to stock (usually preferred)
        - Options.  This is a right to purchase stock at a particular price.  Usually
                    granted to employees, and usually is for common stock.
        - Warrants. This is a right to purchased stock at a particuar price.  Usually
                    granted to investors, and is usually for preferred stock.""")
    conversion_ratio = models.FloatField(blank=True, null=True, help_text="""
        Preferred shares may convert into common shares at a factor other
        than 1:1.  The conversion ratio represents that conversion factor.  If
        a convertible, this should also be set to the conversion ratio of the
        security into which the convertible defaults under change of control.""")
    liquidation_preference = models.FloatField(blank=True, null=True, help_text="""
        In a liquidation preferred shares may receive proceeds differently
        than common shares.  The most common of these 'preferences' is the
        liquidation preference, which ensures that the preferred stock is
        paid before common stock in a company sale.  This variable represents
        the factor of initial principal to be returned before common is paid.
        1 X is typical.  NOTE: While convertibles do not
        have a direct liquidation preference, they will adopt the preference of
        the security into which they convert.  Therefore, be sure to add that
        preference here for convertibles as well.  If you can not determine
        what that preference will be in a default liquidation because it is
        not codified, then get that squared away with your investors immediately.""")
    is_participating = models.BooleanField(default=False, help_text="""
        If true, the peferred security participates along with common stock
        in addition to the liqudation preference.""")
    participation_cap = models.FloatField(blank=True, null=True, help_text="""
        If 'is participating' is true, refers to the cap participation in
        liquidation.  Set this to zero for a fully participating security.""")
    price_per_share = models.FloatField(blank=True, null=True, help_text="""
        For equity, this is the actual price-per-share paid as
        indicated on the term sheet (or from the proforma.)  For rights
        (ie, options and warrants) this is the strike price at which the
        underlying security may be purchased.  For convertible debt, this
        represents the default price at which the convertible will be
        exchanged if there is a change of control before a financing event. """)
    price_cap = models.IntegerField(blank=True, null=True, help_text="""
        Specific to convertible notes: the valuation cap from which a price per
        share will be derived at conversion (at the next round of financing.)""")
    discount_rate = models.FloatField(blank=True, null=True, help_text="""
        Specific to convertible notes: the discount rate at which the debt will covert
        assuming that there is no price-cap or the price cap is not met.""")
    interest_rate = models.FloatField(blank=True, null=True, help_text="""
        Specific to debt, the interest rate of the loan (assumed to be simple interest.)""")
    pre = models.FloatField(blank=True, null=True, help_text="""

project/templates/captable/certificate.html
{% extends 'base.html' %}

{% block title %}
  <title>
    Certificate Detail
  </title>
{% endblock title %}

{% block content %}
  <div class='container'>
    {{certificate.name}}<br><br>

    {% for t in transactions %}
      {{t.date}}, - {{t.notes}}<br>
    {% endfor %}
  </div><!--/container-->
{% endblock content %}

project/templates/captable/certificates.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}

{% block title %}
  <title>
    Certificate List
  </title>
{% endblock title %}

{% block content %}
  {% render_table table %}
{% endblock content %}

project/templates/captable/investor.html
{% extends 'base.html' %}


{% block title %}
  <title>
    Investor Detail
  </title>
{% endblock title %}


{% block content %}
<div class='container'>
  {{investor}}<br><br>
  <strong>Related Funds</strong><br>
  {% for shareholder in investor.shareholder_set.all %}
    {{shareholder}}<br>
  {% endfor %}<br><br>
  {% for certificate in certificates %}
    {{certificate.shareholder.name}}, {{certificate.name}}<br>
  {% endfor %}

  {% if investor.contact %}
    <strong>Contact</strong><br>
    {{investor.contact}}<br>
    {{investor.address}}<br>
    {{investor.city}}, {{investor.state}}  {{investor.zipcode}}
  {% endif %}
</div><!--container-->
{% endblock content %}

project/templates/captable/investors.html
{% extends 'base.html' %}

{% block title %}
  <title>
    Investor List
  </title>
{% endblock title %}


{% block content %}
  <div class='container'>
    {% for investor in investors %}
      <a href="{% url 'captable:investor' investor.slug %}">{{investor.name}}</a><br>
    {% endfor %}
  </div><!--/container-->
{% endblock content %}

project/templates/captable/securities.html
{% extends 'base.html' %}

{% block title %}
  <title>
    Security List
  </title>
{% endblock title %}


{% block content %}
  <div class='container'>
    {% for security in securities %}
      <a href="{% url 'captable:security' security.slug %}">{{security.name}}</a><br>
    {% endfor %}
  </div><!--/container-->
{% endblock content %}

project/templates/captable/security.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}


{% block title %}
<title>
  Security Detail
</title>
{% endblock title %}

{% block content %}
  <div class='container'>
    {{security}}, {{security.date}}<br>
    {% render_table table %}
  </div><!--/container-->
{% endblock content %}

project/templates/captable/shareholder.html
{% extends 'base.html' %}

{% block title %}
  <title>
    Shareholder Detail
  </title>
{% endblock title %}

{% block content %}
  <div class='container'>
    {{security}}, {{security.date}}<br>
    {% for shareholder in security.transaction.shareholder_set.all %}
      {{shareholder}}<br>
    {% endfor %}
  </div><!--/container-->
{% endblock content %}

project/templates/captable/shareholders.html
{% extends 'base.html' %}

{% load render_table from django_tables2 %}


{% block title %}
  <title>
    Shareholder List
  </title>
{% endblock title %}


{% block content %}
  <div class='container'>
    {% render_table table %}
  </div><!--/container-->
{% endblock content %}

project/templates/captable/summary.html
{% extends 'base.html' %}
{% load humanize %}
{% load captabletags %}

{% block title %}
  <title>
    Summary Capitalization
  </title>
{% endblock title %}

{% block summary-active %}
  active
{% endblock summary-active %}

{% block content %}
  <div class='container'>
    {# <a href = "{% url 'company' company.slug %}">{{company.name}}</a><br> #}
    <table class="table table-bordered table-hover table-summary">
    <caption>Summary Capitalization</caption>
      <thead>
        <tr>
          <th>Type</th>
          <th>Series Name</th>
          <th>Conversion Ratio</th>
          <th>Authorized</th>
          <th>Shares Outstanding</th>
          <th>as Converted</th>
          <th>Rata Diluted</th>
        </tr>
      </thead>
      <tbody>
      {% regroup securities by get_security_type_display as security_list_by_type %}
      {% for security_by_type in security_list_by_type %}
        <tr>
          <th class="table-h2" colspan='4'>{{security_by_type.grouper}}</th>
          <th>{# type subtotal #}</th>
          <th></th>
          <th>{# rata subtotal #}</th>
        </tr>
        {% for item in security_by_type.list %}
          <tr class='table-item'>
            <td></td>
            <td><a href="{% url 'captable:security' item.slug %}">{{item.name}}</a></td>
            <td>{{item.conversion_ratio|default_if_none:""}}</td>
            <td>{{item.authorized|default_if_none:""|intcomma}}</td>
            <td>{{item.outstanding|default_if_none:""|floatformat:0|intcomma}}</td>
            <td>{{item.converted|floatformat:0|intcomma}}</td>
            <td>{{item.diluted_rata|percentage}}</td>
          </tr>
        {% endfor item %}
      {% endfor security_list_by_type %}
        <tr>
          <td>Remaining Options Available</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>{{company.available|floatformat:0|intcomma}}</td>
          <td>{{company.available_rata|percentage}}</td>
        </tr>
        <tr>
          <th colspan='4'>Totals</th>
          <th>{{company.outstanding|floatformat:0|intcomma}}</th>
          <th>{{company.diluted|floatformat:0|intcomma}}</th>
          <th>{{company.diluted_rata|percentage}}</th>
        </tr>
      </tbody>
    </table>
  </div> <!-- /container -->
{% endblock content %}

{% block footer %}
  Prepared on {% now "r" %}
{% endblock footer %}